In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print("Ready for data analysis!")

Ready for data analysis!

In [19]:
data = {
    "name": ["Noa", "Dana", "Tom", "Maya", "Yuval"],
    "age": [21, 31, 27, 25, 29],
    "sessions": [12, 7, 18, 15, 5],
    "purchases": [3, 1, 6, 4, 0]
}

df = pd.DataFrame(data)

df

    name  age  sessions  purchases
0    Noa   21        12          3
1   Dana   31         7          1
2    Tom   27        18          6
3   Maya   25        15          4
4  Yuval   29         5          0

In [4]:
df.describe()

             age   sessions  purchases
count   5.000000   5.000000   5.000000
mean   27.200000  11.400000   2.800000
std     2.863564   5.412947   2.387467
min    24.000000   5.000000   0.000000
25%    25.000000   7.000000   1.000000
50%    27.000000  12.000000   3.000000
75%    29.000000  15.000000   4.000000
max    31.000000  18.000000   6.000000

In [6]:
df.groupby("age")["purchases"].mean()

age
24    3.0
25    4.0
27    6.0
29    0.0
31    1.0
Name: purchases, dtype: float64

In [7]:
df.groupby("age")[["sessions", "purchases"]].mean()

     sessions  purchases
age
24       12.0        3.0
25       15.0        4.0
27       18.0        6.0
29        5.0        0.0
31        7.0        1.0

In [9]:
bins = [18, 25, 30, 35, 45, float("inf")]

labels = [
    "18-24",
    "25-29",
    "30-34",
    "35-44",
    "45+"
]
df["age_group"] = pd.cut(
    df["age"],
    bins=bins,
    labels=labels,
    right=False
)
df

    name  age  sessions  purchases age_group
0    Noa   24        12          3     18-24
1   Dana   31         7          1     30-34
2    Tom   27        18          6     25-29
3   Maya   25        15          4     25-29
4  Yuval   29         5          0     25-29

In [13]:
age_analysis = df.groupby("age_group", observed=True).agg(
    users=("name", "count"),
    total_sessions=("sessions", "sum"),
    avg_sessions=("sessions", "mean"),
    total_purchases=("purchases", "sum"),
    avg_purchases=("purchases", "mean")
)

age_analysis

           users  total_sessions  avg_sessions  total_purchases  avg_purchases
age_group
18-24          1              12     12.000000                3       3.000000
25-29          3              38     12.666667               10       3.333333
30-34          1               7      7.000000                1       1.000000

In [20]:
# מספר קבוצות הגיל שאנחנו רוצות
n_groups = 3

# יצירת קבוצות גיל עם מספר דומה של אנשים בכל קבוצה
age_bins = pd.qcut(
    df["age"],
    q=n_groups,
    duplicates="drop"
 )
df["age_group"] = age_bins.map(
    lambda age_range: f"{int(age_range.left)}-{int(age_range.right)}"
 )

# יצירת טבלת סיכום
age_analysis = (
    df.groupby("age_group", observed=True)
      .agg(
          users=("age", "count"),
          avg_age=("age", "mean"),
          total_sessions=("sessions", "sum"),
          avg_sessions=("sessions", "mean"),
          total_purchases=("purchases", "sum"),
          avg_purchases=("purchases", "mean")
      )
      .reset_index()
 )

age_analysis

,age_group,users,avg_age,total_sessions,avg_sessions,total_purchases,avg_purchases
0,20-25,2,23.0,27,13.5,7,3.5
1,25-28,1,27.0,18,18.0,6,6.0
2,28-31,2,30.0,12,6.0,1,0.5

In [ ]:
print("change 2")